### ISSUE TITLE
validation errors/warnings

### ISSUE THREAD

**Issue by xueyuanjia** [w3c/json-ld-framing#124]
Hello,

@shujikamitsuna (Thank you!) noted the following [validator](https://validator.w3.org) errors/warnings in the [JSON-LD 1.1 Framing Recommendation](https://www.w3.org/TR/2020/REC-json-ld11-framing-20200716/) while developing a [Japanese translation](https://www.asahi-net.or.jp/~ax2s-kmtn/internet/lod/REC-json-ld11-framing-20200716.html):

* [HTML](https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.w3.org%2FTR%2F2020%2FREC-json-ld11-framing-20200716%2F)
* [CSS](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fwww.w3.org%2FTR%2F2020%2FREC-json-ld11-framing-20200716%2F&profile=css3svg&usermedium=all&warning=1&vextwarning=)
* [Link Check](https://validator.w3.org/checklink?uri=https%3A%2F%2Fwww.w3.org%2FTR%2F2020%2FREC-json-ld11-framing-20200716%2F&hide_type=all&depth=&check=Check)

Would you like to take a look?

Thank you!
Xueyuan

**Comment by pchampin** [comment]
* The HTML warnings are due to an old bug in Respec, which has been fixed since:
    w3c/respec#3584

* The CSS errors and warning actually come from a common W3C stylesheet...
     https://www.w3.org/StyleSheets/TR/2016/base.css

* Re. the link checker:
  * the only 404 is due to the fact that the `master` branch on github was renamed to `main`, according to good practices; so the link was valid when the document was published... The current editor's draft contains the correct link.
  * the reported "broken fragments" are spurious errors -- the destination page is dynamically interpreting the fragments
  * the two 308 redirect do no harm but could easily be fixed (http to https redirection) → fixed in editors draft

To conclude: these errors are either outside of our control or already fixed in the latest editor's draft.

I am not sure whether they deserve a new publication of the REC, though...?
