### ISSUE TITLE
Define media profile for frames

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-framing#21]
At some point, the Mime type defined in [IANA Considerations](https://www.w3.org/TR/json-ld11-framing/#iana-considerations) needs to be registered. We should update the contact and probably to @iherman.

**Comment by iherman** [comment]
Fine with me. We can then proceed through the usual route. But I guess it is too early to register, isn't it?

**Comment by azaroth42** [comment]
Why do we need a separate media type, rather than registering a profile for application/ld+json like expanded or compacted?

Frames are just JSON-LD documents that have special processing implications when applied to other JSON-LD documents.

As Framing does not have backwards compatibility requirements, I think we should consider our options. Especially with respect to https://github.com/w3c/dxwg/issues/261.

**Comment by BigBlueHat** [comment]
@gkellogg in as much as the direct processing model is identical to `application/ld+json`) and only the context (sorry) in which it's used changes it's "meaning"--i.e. makes it a "frame" vs. a data document--I'd recommend avoiding another media type and leaning on `profile` as done for compact, expanded, and flattended: https://www.iana.org/assignments/profile-uris/profile-uris.xhtml

That said, there could be a case made for the MIME type registration's value in association with editors and file extensions...but sadly you can't state a file extension for non-Web use in association with a `profile=""` registry entry (which would've been nice for Web Annotation...).

**Comment by BigBlueHat** [comment]
Also fixed a wee typo in that section in 120c32b

**Comment by gkellogg** [comment]
A frame does have some elements that a normal JSON-LD document wouldn't, such as `@default` and other flags. But, it is a subtle distinction. I could see using a profile instead of an independent type.

@BigBlueHat that wasn't a typo, but it is debatable if `application/frame-ld+json` is better (or more correct) than `application/ld-frame+json`.

**Comment by gkellogg** [comment]
If they're inconsistent, then we should pick one. However, I think the profile solution is likely best.

**Comment by BigBlueHat** [comment]
@gkellogg could you change the title here to reflect this new proposal? Or close in favor of an issue focused on the `profile` proposal?

I'd like to get it on the agenda for a future call.

**Comment by BigBlueHat** [comment]
Related to https://github.com/w3c/json-ld-syntax/issues/8

**Comment by iherman** [comment]
Define media profile for frames
Adam Soroka: https://github.com/w3c/json-ld-framing/issues/21

Adam Soroka: https://github.com/w3c/json-ld-framing/issues/28

Gregg Kellogg: the framing document that did not become a rec has a mimetype in it
… but that was a bad idea– we have profiles!
… we have a profile param that identifies a context
… we don’t require that the context be published with that profile
… should we require that of frames?
… you might want to do that because frames use different keywords

Rob Sanderson: if you push a frame document into a regular JSON-LD proc, it should beef

Gregg Kellogg: [describes framing in general]

Rob Sanderson: ref: https://www.w3.org/TR/json-ld11-framing/ ;)

Ivan Herman: gkellogg: should this be a profile or a separate mediatype?

Ivan Herman: a mediatype points to a specific document that describes that mediatype. those docs are different in this case, so the mediatypes should be different

Gregg Kellogg: using the parameter would allow us to negotiate for a context

David Newbury: thinking about the IIIF use case, being able to request docs as either a context or a frame

Gregg Kellogg: if you reference a context but it comes back as a frame, you could change you inx model to account for that

David Newbury: IIIF use a “context” as we use a “profile”, e.g. to include a version
… but that seems okay because we could do it either way

Gregg Kellogg: we describe the behavior of downloading a context and we would need to account for this there.

Ivan Herman: if you don’t register a new mediatype for frame, we will have to change our docs, so which one requires more work?

Rob Sanderson: if we say separate mediatype, we need tests for that
… frames out there in the wild would now fail

Rob Sanderson: if that is decisive, we should rec that a profile SHOULD be used
… to avoid that

Proposed resolution: Use ld+json with a profile for media type of frames, import frame keywords to syntax with reference out. (Rob Sanderson)

Rob Sanderson: +1

Ivan Herman: +1

Harold Solbrig: +1

Gregg Kellogg: +1

Simon Steyskal: +1

Adam Soroka: +1

David I. Lehn: +1

Jeff Mixter: +1

David Newbury: +1

Benjamin Young: +1

Resolution #7: Use ld+json with a profile for media type of frames, import frame keywords to syntax with reference out. {: #resolution7 .resolution}

Proposed resolution: the use of the media type for a frame is RECOMMENDED not a MUST (Rob Sanderson)

Rob Sanderson: +1

Ivan Herman: +1

Adam Soroka: +1

Gregg Kellogg: +1

Simon Steyskal: +1

David Newbury: +1

David I. Lehn: +1

Harold Solbrig: +1

Resolution #8: the use of the media type for a frame is RECOMMENDED not a MUST {: #resolution8 .resolution}

Jeff Mixter: +1

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-02-08-json-ld#section5-3).

- `RESOLVED:  Use ld+json with a profile for media type of frames, import frame keywords to syntax with reference out. {: #resolution7 .resolution}`
- `RESOLVED:  the use of the media type for a frame is RECOMMENDED not a MUST {: #resolution8 .resolution}`
<details><summary><i class="differentiate">View the transcript</i></summary>
Define media profile for frames<br/>
Adam Soroka: <a href="https://github.com/w3c/json-ld-framing/issues/21">https://github.com/w3c/json-ld-framing/issues/21</a><br/>
Adam Soroka: <a href="https://github.com/w3c/json-ld-framing/issues/28">https://github.com/w3c/json-ld-framing/issues/28</a><br/>
Gregg Kellogg: the framing document that did not become a rec has a mimetype in it<br/>
… but that was a bad idea– we have profiles!<br/>
… we have a profile param that identifies a context<br/>
… we don’t require that the context be published with that profile<br/>
… should we require that of frames?<br/>
… you might want to do that because frames use different keywords<br/>
Rob Sanderson: if you push a frame document into a regular JSON-LD proc, it should beef<br/>
Gregg Kellogg: [describes framing in general]<br/>
Rob Sanderson: ref: <a href="https://www.w3.org/TR/json-ld11-framing/">https://www.w3.org/TR/json-ld11-framing/</a> ;)<br/>
Ivan Herman: gkellogg: should this be a profile or a separate mediatype?<br/>
Ivan Herman: a mediatype points to a specific document that describes that mediatype. those docs are different in this case, so the mediatypes should be different<br/>
Gregg Kellogg: using the parameter would allow us to negotiate for a context<br/>
David Newbury: thinking about the IIIF use case, being able to request docs as either a context or a frame<br/>
Gregg Kellogg: if you reference a context but it comes back as a frame, you could change you inx model to account for that<br/>
David Newbury: IIIF use a “context” as we use a “profile”, e.g. to include a version<br/>
… but that seems okay because we could do it either way<br/>
Gregg Kellogg: we describe the behavior of downloading a context and we would need to account for this there.<br/>
Ivan Herman: if you don’t register a new mediatype for frame, we will have to change our docs, so which one requires more work?<br/>
Rob Sanderson: if we say separate mediatype, we need tests for that<br/>
… frames out there in the wild would now fail<br/>
Rob Sanderson: if that is decisive, we should rec that a profile SHOULD be used<br/>
… to avoid that<br/>
Proposed resolution: Use ld+json with a profile for media type of frames, import frame keywords to syntax with reference out. (Rob Sanderson)<br/>
Rob Sanderson: +1<br/>
Ivan Herman: +1<br/>
Harold Solbrig: +1<br/>
Gregg Kellogg: +1<br/>
Simon Steyskal: +1<br/>
Adam Soroka: +1<br/>
David I. Lehn: +1<br/>
Jeff Mixter: +1<br/>
David Newbury: +1<br/>
Benjamin Young: +1<br/>
Resolution #7: Use ld+json with a profile for media type of frames, import frame keywords to syntax with reference out. {: #resolution7 .resolution}<br/>
Proposed resolution: the use of the media type for a frame is RECOMMENDED not a MUST (Rob Sanderson)<br/>
Rob Sanderson: +1<br/>
Ivan Herman: +1<br/>
Adam Soroka: +1<br/>
Gregg Kellogg: +1<br/>
Simon Steyskal: +1<br/>
David Newbury: +1<br/>
David I. Lehn: +1<br/>
Harold Solbrig: +1<br/>
Resolution #8: the use of the media type for a frame is RECOMMENDED not a MUST {: #resolution8 .resolution}<br/>
Jeff Mixter: +1<br/>
</details>

**Comment by akuckartz** [comment]
I do not understand the resolution. Was it in favor of a specific Media Type for frames or not?

**Comment by iherman** [comment]
@akuckartz : the idea is that the syntax document, more exactly the grammar of JSON-LD, should include the frame specific terms, too, which means that, from a media type point of view, a frame document would be a bona fide JSON-LD document. Ie, no need for a separate media type.
