### ISSUE TITLE
Frames are indistinguishable from other JSON-LD documents

### ISSUE THREAD

**Issue by azaroth42** [w3c/json-ld-framing#28]
Frames are just JSON-LD documents, but result in special processing. #21 is to register a new IANA media type for frames, but is this sufficient or should the document be recognizable without the HTTP response context?

**Comment by BigBlueHat** [comment]
This seems like the same situation as when a JSON-LD file typically used as a context document also contains its own data. It's a valuable feature, but does lead to some confusion of intent.

Maybe we need a pros/cons list for the value/risk of using a single JSON-LD document as a context, a frame, and a data document?

**Comment by iherman** [comment]
Define media profile for frames
Adam Soroka: https://github.com/w3c/json-ld-framing/issues/21

Adam Soroka: https://github.com/w3c/json-ld-framing/issues/28

Gregg Kellogg: the framing document that did not become a rec has a mimetype in it
… but that was a bad idea– we have profiles!
… we have a profile param that identifies a context
… we don’t require that the context be published with that profile
… should we require that of frames?
… you might want to do that because frames use different keywords

Rob Sanderson: if you push a frame document into a regular JSON-LD proc, it should beef

Gregg Kellogg: [describes framing in general]

Rob Sanderson: ref: https://www.w3.org/TR/json-ld11-framing/ ;)

Ivan Herman: gkellogg: should this be a profile or a separate mediatype?

Ivan Herman: a mediatype points to a specific document that describes that mediatype. those docs are different in this case, so the mediatypes should be different

Gregg Kellogg: using the parameter would allow us to negotiate for a context

David Newbury: thinking about the IIIF use case, being able to request docs as either a context or a frame

Gregg Kellogg: if you reference a context but it comes back as a frame, you could change you inx model to account for that

David Newbury: IIIF use a “context” as we use a “profile”, e.g. to include a version
… but that seems okay because we could do it either way

Gregg Kellogg: we describe the behavior of downloading a context and we would need to account for this there.

Ivan Herman: if you don’t register a new mediatype for frame, we will have to change our docs, so which one requires more work?

Rob Sanderson: if we say separate mediatype, we need tests for that
… frames out there in the wild would now fail

Rob Sanderson: if that is decisive, we should rec that a profile SHOULD be used
… to avoid that

Proposed resolution: Use ld+json with a profile for media type of frames, import frame keywords to syntax with reference out. (Rob Sanderson)

Rob Sanderson: +1

Ivan Herman: +1

Harold Solbrig: +1

Gregg Kellogg: +1

Simon Steyskal: +1

Adam Soroka: +1

David I. Lehn: +1

Jeff Mixter: +1

David Newbury: +1

Benjamin Young: +1

Resolution #7: Use ld+json with a profile for media type of frames, import frame keywords to syntax with reference out. {: #resolution7 .resolution}

Proposed resolution: the use of the media type for a frame is RECOMMENDED not a MUST (Rob Sanderson)

Rob Sanderson: +1

Ivan Herman: +1

Adam Soroka: +1

Gregg Kellogg: +1

Simon Steyskal: +1

David Newbury: +1

David I. Lehn: +1

Harold Solbrig: +1

Resolution #8: the use of the media type for a frame is RECOMMENDED not a MUST {: #resolution8 .resolution}

Jeff Mixter: +1

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-02-08-json-ld#section5-3).

- `RESOLVED:  Use ld+json with a profile for media type of frames, import frame keywords to syntax with reference out. {: #resolution7 .resolution}`
- `RESOLVED:  the use of the media type for a frame is RECOMMENDED not a MUST {: #resolution8 .resolution}`
<details><summary><i class="differentiate">View the transcript</i></summary>
Define media profile for frames<br/>
Adam Soroka: <a href="https://github.com/w3c/json-ld-framing/issues/21">https://github.com/w3c/json-ld-framing/issues/21</a><br/>
Adam Soroka: <a href="https://github.com/w3c/json-ld-framing/issues/28">https://github.com/w3c/json-ld-framing/issues/28</a><br/>
Gregg Kellogg: the framing document that did not become a rec has a mimetype in it<br/>
… but that was a bad idea– we have profiles!<br/>
… we have a profile param that identifies a context<br/>
… we don’t require that the context be published with that profile<br/>
… should we require that of frames?<br/>
… you might want to do that because frames use different keywords<br/>
Rob Sanderson: if you push a frame document into a regular JSON-LD proc, it should beef<br/>
Gregg Kellogg: [describes framing in general]<br/>
Rob Sanderson: ref: <a href="https://www.w3.org/TR/json-ld11-framing/">https://www.w3.org/TR/json-ld11-framing/</a> ;)<br/>
Ivan Herman: gkellogg: should this be a profile or a separate mediatype?<br/>
Ivan Herman: a mediatype points to a specific document that describes that mediatype. those docs are different in this case, so the mediatypes should be different<br/>
Gregg Kellogg: using the parameter would allow us to negotiate for a context<br/>
David Newbury: thinking about the IIIF use case, being able to request docs as either a context or a frame<br/>
Gregg Kellogg: if you reference a context but it comes back as a frame, you could change you inx model to account for that<br/>
David Newbury: IIIF use a “context” as we use a “profile”, e.g. to include a version<br/>
… but that seems okay because we could do it either way<br/>
Gregg Kellogg: we describe the behavior of downloading a context and we would need to account for this there.<br/>
Ivan Herman: if you don’t register a new mediatype for frame, we will have to change our docs, so which one requires more work?<br/>
Rob Sanderson: if we say separate mediatype, we need tests for that<br/>
… frames out there in the wild would now fail<br/>
Rob Sanderson: if that is decisive, we should rec that a profile SHOULD be used<br/>
… to avoid that<br/>
Proposed resolution: Use ld+json with a profile for media type of frames, import frame keywords to syntax with reference out. (Rob Sanderson)<br/>
Rob Sanderson: +1<br/>
Ivan Herman: +1<br/>
Harold Solbrig: +1<br/>
Gregg Kellogg: +1<br/>
Simon Steyskal: +1<br/>
Adam Soroka: +1<br/>
David I. Lehn: +1<br/>
Jeff Mixter: +1<br/>
David Newbury: +1<br/>
Benjamin Young: +1<br/>
Resolution #7: Use ld+json with a profile for media type of frames, import frame keywords to syntax with reference out. {: #resolution7 .resolution}<br/>
Proposed resolution: the use of the media type for a frame is RECOMMENDED not a MUST (Rob Sanderson)<br/>
Rob Sanderson: +1<br/>
Ivan Herman: +1<br/>
Adam Soroka: +1<br/>
Gregg Kellogg: +1<br/>
Simon Steyskal: +1<br/>
David Newbury: +1<br/>
David I. Lehn: +1<br/>
Harold Solbrig: +1<br/>
Resolution #8: the use of the media type for a frame is RECOMMENDED not a MUST {: #resolution8 .resolution}<br/>
Jeff Mixter: +1<br/>
</details>

**Comment by iherman** [comment]
Hm. I am a bit bothered, but maybe for no good reasons.

The frame objects allow for, say, something like `"@id":{}`, right? But that means I can put this into any context whatsover: what does it mean?

In general, there is nothing that distinguish a frame object from any other constituents of a context, so is it absolutely clear what the API does if it encounters such statements as part of normal processing like expansion? If there is already (I presume ignoring) that should be made much more clearly in the document.

**Comment by gkellogg** [comment]
The expansion algorithm will throw an error unless it is invoked with a _framing_ option.

There are some other things that are legal for frames that don’t involve keywords that we should describe as well, but the would all be either in frame objects, or immediate values of frame objects.
