### ISSUE TITLE
Provide an option for all terms to get a default "@container"

### ISSUE THREAD

**Issue by michaelcpuckett** [w3c/json-ld-framing#31]
I would like to have all my relational data come back as arrays of IDs.

Right now I have to add the following to `@context` for each term:

```
      "foo": {
        "@container": "@set",
        "@type": "@id"
      },
```

I propose a processor option (similar to `embed`) that would allow a default `container`.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-02-08-json-ld#section5-8).

- `RESOLVED:  Close framing #31, wontfix, with request for further discussion if they can provide more information to support its inclusion {: #resolution13 .resolution}`
- `ACTION:  Rob Sanderson to put comment in to #31 requesting more info`
<details><summary><i class="differentiate">View the transcript</i></summary>
Provide an option for all terms to get a default "@container"<br/>
Rob Sanderson: ref: <a href="https://github.com/w3c/json-ld-framing/issues/31">https://github.com/w3c/json-ld-framing/issues/31</a><br/>
Gregg Kellogg: I had discussed putting in a default container set unless set otherwise.<br/>
… which is less disruptive than the graph id<br/>
… not a framing issue, but a compaction issue<br/>
Rob Sanderson: just a convenience mechanism<br/>
… is the value of this higher enough to warrant a new default?<br/>
Gregg Kellogg: can’t be done in framing, must be in compaction.<br/>
… is it valuable enough?<br/>
Ivan Herman: this is what schema would do. They are very systematic in mapping this.<br/>
… this will make schema.org will get there automatically<br/>
Gregg Kellogg: currently, list and set are incompatible, though we’ve discussed this.<br/>
David Newbury: .. one used to be ordered, and one unordered…but we’ve overridden that already.<br/>
Rob Sanderson: for this issue, if you were to set a default container at @language<br/>
Gregg Kellogg: that would be scary. Everything would be a language map.<br/>
… and you’d have to define that.<br/>
Rob Sanderson: if you snuck this away…<br/>
Rob Sanderson: how would you undo this if it was @set?<br/>
Gregg Kellogg: … empty array? @container: null?<br/>
Rob Sanderson: in my opinion, the value is outweighed by the danger<br/>
David Newbury: I don’t think that we need better ergonomics for creating contexts…<br/>
Rob Sanderson: so we propose that this is valuable, but can they provide more use cases other than it being a bit redundant?<br/>
Proposed resolution: push back to original commenter, asking for more use cases. Saving context authors some keystrokes is not a high priority (Rob Sanderson)<br/>
David Newbury: +1<br/>
Jeff Mixter: +1<br/>
Rob Sanderson: +1<br/>
Gregg Kellogg: +1<br/>
Ivan Herman: +1<br/>
Rob Sanderson: …<br/>
Proposed resolution: Close framing #31, wontfix, with request for further discussion if they can provide more information to support its inclusion (Rob Sanderson)<br/>
David Newbury: +1<br/>
Rob Sanderson: +1<br/>
Ivan Herman: +1<br/>
Jeff Mixter: +1<br/>
David I. Lehn: +1<br/>
Action #2: Rob Sanderson to put comment in to #31 requesting more info<br/>
Gregg Kellogg: +1<br/>
Harold Solbrig: +1<br/>
Resolution #13: Close framing #31, wontfix, with request for further discussion if they can provide more information to support its inclusion {: #resolution13 .resolution}<br/>
</details>

**Comment by michaelcpuckett** [comment]
Thanks @iherman for reviewing this.

For my specific case, I want to model my data based on schema.org. I want to keep a generic, reusable frame and have the schema.org `@vocab` do the heavy lifting of mapping the relationships. Unfortunately I must define every schema.org term I might use in the `@context`. If these could all be set to a default, I would not need to have complete knowledge of the vocabulary I'm using.

```
jsonld.frame(json, {
  "@context": {
    "@vocab": "http://schema.org/",
    "agent": {
      "@container": "@set",
      "@type": "@id"
    },
    "participant": {
      "@container": "@set",
      "@type": "@id"
    },
    "recipient": {
      "@container": "@set",
      "@type": "@id"
    },
    "author": {
      "@container": "@set",
      "@type": "@id"
    },
    ...
  },
})
```

If there is a simpler way to achieve this, please let me know.

**Comment by azaroth42** [comment]
Thanks @michaelcpuckett ! There isn't an easier way to do it I'm afraid, as the situation where _every_ term in a vocabulary should always be `@container: @set` is vanishingly small. It would mean that every relationship was aways one to many or many to many, and never one to one or one to many.  (It's also a syntax issue for compaction via setting a context, rather than a framing issue per se, but that's not a big deal)

My understanding of the intent of `@vocab` is to provide a default mapping from JSON _to_ RDF, rather than a default mapping _from_ RDF into a particular JSON structure. We have heard from several parties that the schema.org approach of just throwing `@vocab` in there and letting the application sort it out is often insufficient, and it seems like you're in the same boat.
