### ISSUE TITLE
Improve example 18 for @omitDefault

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-framing#46]
The example works, but does not really show why you would ever use both `@default` and `@omitDefault`.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-03-22-json-ld#section1-1).

- `ACTION:  provide example in issue frame/41 of @omitdefault need (Dave Longley)`
<details><summary><i class="differentiate">View the transcript</i></summary>
Remove @omitdefault<br/>
Rob Sanderson: link: <a href="https://github.com/w3c/json-ld-framing/issues/41">https://github.com/w3c/json-ld-framing/issues/41</a><br/>
Gregg Kellogg: also: <a href="https://github.com/w3c/json-ld-framing/issues/46">https://github.com/w3c/json-ld-framing/issues/46</a><br/>
Rob Sanderson: The first issue we discussed briefly last call before we realized we needed to talk a bit more about it.<br/>
Gregg Kellogg: Another issue is to provide a better example for its use.<br/>
… Of @omitDefault.<br/>
… The issue is suggesting that @omitDefault is not particularly useful when you can just omit when using default. I think Dave had alluded to some examples where it was useful and that’s why there’s an issue open to highlight where it’s actually useful.<br/>
… Otherwise we could remove it from the spec.<br/>
… The only way to make a default is to use @default.<br/>
Dave Longley: There’s a few ways to have a default. There’s an interaction with explicit. A default of null, if the property is specified but not present. Then output has a default value of null<br/>
… sometimes you don’t want it with a value of null, but instead absent.<br/>
… Also, if you had specified a default, and some other properties to have flags on them.<br/>
… a case would be when you say ‘foo’ and you want to embed:always for foo.<br/>
… [example]<br/>
Gregg Kellogg: Ok, I think you’ve made a case for why it needs to be there. Having implemented it I still don’t understand the need for it. As long as you take on the responsibility of better documenting the use of @omitDefault.<br/>
… If you can provide an example so we can adequately spec it that would be sufficient.<br/>
Action #1: provide example in issue frame/41 of @omitdefault need (Dave Longley)<br/>
</details>

**Comment by azaroth42** [comment]
Example in #41 seems very clear to me!

**Comment by dlongley** [comment]
@gkellogg,

> The example works, but does not really show why you would ever use both `@default` and `@omitDefault`.

The issue isn't with specifying those two flags *together*, but rather that there is a "default `@default`" of `null` that you may want to selectively disable. This is particularly true when you need to specify other flags (like `@embed` as in the example). I agree that it would be silly to use both `@omitDefault` and `@default` on the same subsection of a frame.
