### ISSUE TITLE
Default value for @type

### ISSUE THREAD

**Issue by AtesComp** [w3c/json-ld-framing#74]
Currently, @type cannot accept @default in the playground.  For framing, the documentation seems to indicate that @type (a keyword) must be a definitive resource for matching and not definable.

So, how is type added via framing?

I assume the answer would be either:
1. "@type": {"@default": "ex:Book"}
2. "@type": {"@default": {"@id": "ex:Book"}}

Since "@type": "@id" is the usual specification, 2 seems redundant.

NOTE: I know, I've bugged about this quite a bit in the main JSON-LD area.  Since framing was proposed as the solution, I'm officially posting the issue here.

**Comment by gkellogg** [comment]
Yes, we did say that framing was the right way to do this, but the framing algorithm doesn't presently allow for this.

Defaults are added in 4.7.4 of the [Framing Algorithm](https://www.w3.org/TR/json-ld11-framing/#framing-algorithm) which iterates over non-keywords, and thus ignores a default for `@type`. It is _probably_ sufficient to update the algorithm to also include `@type`.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-10-18-json-ld#section2-3).

- `RESOLVED:  Accept framing #74 as an oversight to be fixed for <code>@type</code> on node objects`
<details><summary><i class="differentiate">View the transcript</i></summary>
<code>@default</code> for <code>@type</code><br/>
Rob Sanderson: <a href="https://github.com/w3c/json-ld-framing/issues/74">https://github.com/w3c/json-ld-framing/issues/74</a><br/>
Rob Sanderson: The only thing you can’t consider <code>@default</code> for is <code>@type.</code><br/>
Gregg Kellogg: Also not <code>@id.</code><br/>
… Framing was mentioned as the proper way to handle these cases, but it does not work right now.<br/>
Rob Sanderson: This fits with our general pattern to allow <code>@type</code> to allow more functionality and context, such as <code>@container</code> and <code>@set.</code><br/>
… While our feature window is closed, we can consider this a bug.<br/>
Dave Longley: This is indeed an oversight, something we can fix.<br/>
Pierre-Antoine Champin: So the idea is that <code>@type</code> with <code>@default</code> would set the type on node object or value objects, or any of them?<br/>
Gregg Kellogg: I think only on node objects.<br/>
… We would have to check the algorithm.<br/>
Dave Longley: I think gkellogg is correct.<br/>
Rob Sanderson: Me too. Otherwise we would open up weird issues with <code>@direction</code> and <code>@value.</code><br/>
Dave Longley: +1 to azaroth<br/>
Proposed resolution: Accept framing #74 as an oversight to be fixed for <code>@type</code> on node objects (Rob Sanderson)<br/>
Gregg Kellogg: +1<br/>
Jeff Mixter: +1<br/>
Rob Sanderson: +1<br/>
Ruben Taelman: +1<br/>
Dave Longley: +1<br/>
Pierre-Antoine Champin: +1<br/>
Ivan Herman: +1<br/>
Resolution #4: Accept framing #74 as an oversight to be fixed for <code>@type</code> on node objects<br/>
</details>

**Comment by azaroth42** [comment]
Resolved, closing :)
