### ISSUE TITLE
Clarify example for omit graph flag

### ISSUE THREAD

**Issue by Fak3** [w3c/json-ld-framing#88]
The spec at https://github.com/w3c/json-ld-framing/blob/master/index.html#L639 says:
> if the omit graph flag is true, the top-level @graph entry may be omitted.

But the output given in the example 4 (Framed library objects) and example 5 (Framed library objects with omitGraph set to false) are exactly the same, making it difficult to understand what the omit graph flag is for.

**Comment by gkellogg** [comment]
Yes, this needs to be updated. The omitGraph flag defaults to true in 1,1 mode, which is the default. Set it to false to get the `@graph` back, or use the 1.0 processor mode for the implied false value.

**Comment by Fak3** [comment]
Btw, I find the name of the flag a bit complicated to understand because of double-negation. I.e. in my mind 'omit' means 'don't include', and I always have to perform this mental exercise to parse 'don't include graph is False' into 'include graph'. Does anyone feels the same nuisance? Would it help to rename it to `includeGraph`?

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-12-20-json-ld#section4-2).

- `RESOLVED:  Update examples 4 & 5 in Framing to be instructive as well as correct and close when updated`
<details><summary><i class="differentiate">View the transcript</i></summary>
omit graph example<br/>
Rob Sanderson: <a href="https://github.com/w3c/json-ld-framing/issues/88">https://github.com/w3c/json-ld-framing/issues/88</a><br/>
Gregg Kellogg: The issuer pointed out that we are using double negation, as omitGraph true is the default.<br/>
… It made more sense in 1.0. But now the default value is reversed.<br/>
… We could rename it in 1.1.<br/>
Rob Sanderson: We probably don’t want to rename it to includeGraph?<br/>
Proposed resolution: Update examples 4 &amp; 5 in Framing to be instructive as well as correct (Rob Sanderson)<br/>
Rob Sanderson: We should update the examples in framing to be more instructive.<br/>
… This is just editorial.<br/>
Proposed resolution: Update examples 4 & 5 in Framing to be instructive as well as correct and close when updated (Rob Sanderson)<br/>
Ivan Herman: +1<br/>
Rob Sanderson: +1<br/>
Tim Cole: +1<br/>
Ruben Taelman: +1<br/>
Jeff Mixter: +1<br/>
Adam Soroka: +1<br/>
Pierre-Antoine Champin: +1<br/>
Gregg Kellogg: +1<br/>
Resolution #3: Update examples 4 & 5 in Framing to be instructive as well as correct and close when updated<br/>
</details>

**Comment by gkellogg** [comment]
@Fak3, please see updated text in PR #91. Please indicate if this satisfies your issue.

**Comment by Fak3** [comment]
Yes, this resolves the issue, thanks

**Comment by gkellogg** [comment]
Reopened for WG to dispose of.
