### ISSUE TITLE
Type Coercion / Node Conversion

### ISSUE THREAD

**Issue by lsimichael** [w3c/json-ld-framing#98]
(See below)

**Comment by michaelcpuckett** [comment]
I have an idea for a future version of JSON-LD Framing.

As a web developer, I would like to receive a JSON document from i.e. a simple API, add a `@context` to it, and perform JSON-LD operations. This light approach has been a big selling point to me for using JSON-LD.

A common response from such an API may include an "id" property as a number (as it is indexed in the source database as an integer), so after applying the `@context` the document may look like this:

```json
{
  "@context": {
    "@base": "http://starwars.com/",
    "@vocab": "http://starwars.com/",
    "id": "@id",
    "type": "@type"
  },
  "id": 123,
  "type": "Human",
  "firstName": "Luke",
  "lastName": "Skywalker"
}
```

The expansion step will generate an error:

`Invalid JSON-LD syntax; "@id" value must a string.`

This makes sense, but my intention in declaring the `@base` was to form the IRI "http://starwars.com/123". I don't think this kind of type coercion is currently possible with JSON-LD.

The alternative would be a blank node with a custom ID property, which is less useful in certain situations.

I propose a framing solution that generates a new triple with the coerced XSD type and removes the original, so that when flattened, it becomes:

```
[
  {
    "@id": "http://starwars.com/123",
    "@type": [
      "http://starwars.com/Human"
    ],
    "http://starwars.com/firstName": [
      {
        "@value": "Luke"
      }
    ],
    "http://starwars.com/lastName": [
      {
        "@value": "Skywalker"
      }
    ]
  }
]
```

As a starting point, I suggest adding a term called `@coerce`.

**Comment by gkellogg** [comment]
This would probably be in compaction/expansion rather than framing. It is somewhat similar to the `useNativeTypes` option for fromRdf. 

It’s a common idiom in JSON, so it’s worthy of future consideration.

**Comment by michaelcpuckett** [comment]
Thanks! I opened a new issue in the other repo.

https://github.com/w3c/json-ld-syntax/issues/335

If that's right, this can be closed.
